spring:
  application:
    name: notes-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/notesdb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/notes-realm

